from __future__ import annotations

from datetime import datetime
from pathlib import Path

from agent.executor import ExecutionResult
from agent.llm_client import DeepSeekClient
from agent.planner import Plan
from agent.skill_loader import Skill


def build_raw_output(results: list[ExecutionResult]) -> str:
    chunks: list[str] = []
    for result in results:
        chunks.append(f"## Skill: {result.skill_name}")
        chunks.append(f"Script: {result.script}")
        chunks.append(f"Exit code: {result.exit_code}")
        chunks.append(f"Duration: {result.duration_seconds:.2f}s")
        if result.stdout.strip():
            chunks.append("### stdout")
            chunks.append(result.stdout.strip())
        if result.stderr.strip():
            chunks.append("### stderr")
            chunks.append(result.stderr.strip())
    return "\n\n".join(chunks)


def fallback_summary(user_request: str, plan: Plan, results: list[ExecutionResult]) -> str:
    output = build_raw_output(results)
    failed = [result.skill_name for result in results if not result.ok]
    status = "部分检查出现异常" if failed else "所有检查已完成"
    return (
        f"# Linux 运维诊断报告\n\n"
        f"## 问题概述\n\n"
        f"用户请求：{user_request}\n\n"
        f"执行状态：{status}。\n\n"
        f"执行来源：{plan.source}。\n\n"
        f"选择原因：{plan.reason}。\n\n"
        f"## 关键证据\n\n"
        f"```text\n{output[:12000]}\n```\n\n"
        f"## 可能原因\n\n"
        f"请根据关键证据中的磁盘、日志、进程或网络状态进一步判断。"
        f"如果某些命令提示权限不足，可以使用 sudo 或在管理员账号下重新运行。\n\n"
        f"## 建议处理步骤\n\n"
        f"1. 先处理高占用、高错误率或失败状态明显的项目。\n"
        f"2. 对日志中重复出现的错误按时间顺序定位原因。\n"
        f"3. 处理前备份关键配置和日志，避免误删。\n\n"
        f"## 涉及的 Linux 命令\n\n"
        f"本次执行的命令由项目 scripts 目录中的受控脚本调用，未执行 AI 动态生成命令。\n\n"
        f"## 风险提示\n\n"
        f"本工具默认只做诊断，不自动删除文件、不重启服务、不修改系统配置。\n"
    )


def create_report(
    user_request: str,
    plan: Plan,
    selected_skills: list[Skill],
    results: list[ExecutionResult],
    reports_dir: Path,
    llm_client: DeepSeekClient | None = None,
    use_llm: bool = True,
) -> Path:
    reports_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    skill_part = "-".join(skill.name for skill in selected_skills)[:80] or "refused"
    path = reports_dir / f"{timestamp}-{skill_part}.md"

    raw_output = build_raw_output(results)
    if use_llm and llm_client and llm_client.available and raw_output.strip():
        try:
            content = llm_client.summarize_report(user_request, raw_output)
        except Exception as exc:
            content = fallback_summary(user_request, plan, results)
            content += f"\n\nDeepSeek 总结失败，已使用本地报告模式：`{exc}`\n"
    else:
        content = fallback_summary(user_request, plan, results)

    header = (
        f"<!-- generated by linux-ops-agent at {timestamp} -->\n\n"
        f"<!-- selected skills: {', '.join(skill.name for skill in selected_skills)} -->\n\n"
    )
    path.write_text(header + content.strip() + "\n", encoding="utf-8")
    return path
