from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from agent.analysis_features import (
    cluster_unknown_errors,
    extract_timeline_events,
    render_error_clusters,
    render_timeline,
)
from agent.llm_client import DeepSeekClient
from agent.local_model import render_local_analysis
from agent.skill_loader import Skill


MAX_ANALYSIS_CHARS = 24000


@dataclass(frozen=True)
class TextFinding:
    title: str
    severity: str
    evidence: tuple[str, ...]
    recommendation: str


@dataclass(frozen=True)
class TextAnalysis:
    analysis_type: str
    source_name: str
    summary: str
    findings: tuple[TextFinding, ...]
    raw_excerpt: str
    used_llm: bool = False
    engine: str = "local_model"


def analyze_text(
    text: str,
    analysis_type: str = "auto",
    source_name: str = "inline text",
    llm_client: DeepSeekClient | None = None,
    use_llm: bool = True,
    skills: dict[str, Skill] | None = None,
) -> TextAnalysis:
    normalized = _normalize_text(text)
    if use_llm and llm_client and llm_client.available and normalized.strip():
        try:
            content = llm_client.analyze_operations_text(
                text=normalized[:MAX_ANALYSIS_CHARS],
                analysis_type=analysis_type,
                source_name=source_name,
            )
            return TextAnalysis(
                analysis_type=analysis_type,
                source_name=source_name,
                summary=content.strip(),
                findings=(),
                raw_excerpt=normalized[:4000],
                used_llm=True,
                engine="deepseek",
            )
        except Exception:
            pass

    local_content = render_local_analysis(
        normalized[:MAX_ANALYSIS_CHARS],
        analysis_type=analysis_type,
        source_name=source_name,
        skills=skills,
    )
    fallback = _fallback_analyze_text(normalized, analysis_type, source_name)
    known_evidence = {item for finding in fallback.findings for item in finding.evidence}
    timeline = render_timeline(extract_timeline_events(normalized))
    clusters = render_error_clusters(cluster_unknown_errors(normalized, known_evidence=known_evidence))
    return TextAnalysis(
        analysis_type=analysis_type,
        source_name=source_name,
        summary=local_content + "\n" + timeline + "\n" + clusters,
        findings=fallback.findings,
        raw_excerpt=normalized[:4000],
        used_llm=False,
        engine="local_model",
    )


def write_analysis_report(analysis: TextAnalysis, reports_dir: Path) -> Path:
    reports_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    safe_source = re.sub(r"[^a-zA-Z0-9_.-]+", "-", analysis.source_name)[:50].strip("-")
    path = reports_dir / f"{timestamp}-text-analysis-{safe_source or 'input'}.md"
    path.write_text(render_analysis_markdown(analysis), encoding="utf-8")
    return path


def render_analysis_markdown(analysis: TextAnalysis) -> str:
    header = (
        f"<!-- generated by linux-ops-agent text analyzer -->\n\n"
        f"# Operations Text Analysis\n\n"
        f"- Source: {analysis.source_name}\n"
        f"- Type: {analysis.analysis_type}\n"
        f"- Engine: {'DeepSeek' if analysis.used_llm else analysis.engine}\n\n"
    )
    if analysis.used_llm or analysis.engine == "local_model":
        return header + analysis.summary.strip() + "\n"

    lines = [header, "## Summary\n", analysis.summary.strip(), "\n\n## Findings\n"]
    if not analysis.findings:
        lines.append("- No obvious high-signal operations issue was detected by local rules.\n")
    for finding in analysis.findings:
        lines.append(f"### [{finding.severity.upper()}] {finding.title}\n\n")
        lines.append("Evidence:\n")
        for item in finding.evidence:
            lines.append(f"- `{_clip(item, 220)}`\n")
        lines.append(f"\nRecommendation: {finding.recommendation}\n\n")

    if analysis.raw_excerpt.strip():
        lines.append("## Raw Excerpt\n\n")
        lines.append("```text\n")
        lines.append(analysis.raw_excerpt[:4000].strip())
        lines.append("\n```\n")
    return "".join(lines)


def _fallback_analyze_text(text: str, analysis_type: str, source_name: str) -> TextAnalysis:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    findings: list[TextFinding] = []

    _add_pattern_finding(
        findings,
        lines,
        title="Disk space pressure",
        severity="high",
        patterns=(r"no space left on device", r"\b(9[0-9]|100)%\b", r"disk.*full", r"磁盘.*满", r"空间不足"),
        recommendation="Check df -h, df -i, large log files, and logrotate before deleting files.",
    )
    _add_pattern_finding(
        findings,
        lines,
        title="Permission or ownership problem",
        severity="medium",
        patterns=(r"permission denied", r"operation not permitted", r"forbidden", r"\b403\b", r"权限"),
        recommendation="Inspect file ownership, parent directory execute permissions, service user, and SELinux/AppArmor status.",
    )
    _add_pattern_finding(
        findings,
        lines,
        title="Port conflict or bind failure",
        severity="high",
        patterns=(r"address already in use", r"bind\(\).*failed", r"端口.*占用", r"port.*already"),
        recommendation="Use ss -tulnp to identify the owning process, then decide whether to change the port or stop the conflicting service.",
    )
    _add_pattern_finding(
        findings,
        lines,
        title="Service dependency is unavailable",
        severity="high",
        patterns=(r"connection refused", r"connect\(\).*failed", r"database.*refused", r"redis.*refused", r"mysql.*refused"),
        recommendation="Check whether the upstream service is running, listening on the expected address, and reachable from the caller.",
    )
    _add_pattern_finding(
        findings,
        lines,
        title="Network timeout",
        severity="medium",
        patterns=(r"connection timed out", r"upstream timed out", r"timeout", r"超时"),
        recommendation="Separate DNS, routing, firewall, service listening, and upstream latency checks.",
    )
    _add_pattern_finding(
        findings,
        lines,
        title="Authentication failures",
        severity="medium",
        patterns=(r"failed password", r"invalid user", r"authentication failure", r"登录失败", r"爆破"),
        recommendation="Count source IPs, check SSH policy, and consider key-only login, rate limiting, or source restrictions.",
    )
    _add_pattern_finding(
        findings,
        lines,
        title="Out-of-memory signal",
        severity="high",
        patterns=(r"out of memory", r"oom", r"killed process", r"cannot allocate memory"),
        recommendation="Correlate OOM logs with top memory processes, swap status, and recent traffic or batch jobs.",
    )
    _add_pattern_finding(
        findings,
        lines,
        title="Nginx upstream failure",
        severity="high",
        patterns=(r"\b502\b", r"\b504\b", r"bad gateway", r"upstream", r"nginx"),
        recommendation="Check nginx error.log, upstream port listening, application status, and dependency logs.",
    )

    summary = _build_fallback_summary(findings, analysis_type, source_name, len(lines))
    return TextAnalysis(
        analysis_type=analysis_type,
        source_name=source_name,
        summary=summary,
        findings=tuple(findings),
        raw_excerpt=text[:4000],
        used_llm=False,
    )


def _add_pattern_finding(
    findings: list[TextFinding],
    lines: list[str],
    title: str,
    severity: str,
    patterns: tuple[str, ...],
    recommendation: str,
) -> None:
    evidence: list[str] = []
    for line in lines:
        lowered = line.lower()
        if any(re.search(pattern, lowered, re.IGNORECASE) for pattern in patterns):
            evidence.append(line)
        if len(evidence) >= 5:
            break
    if evidence:
        findings.append(
            TextFinding(
                title=title,
                severity=severity,
                evidence=tuple(evidence),
                recommendation=recommendation,
            )
        )


def _build_fallback_summary(
    findings: list[TextFinding],
    analysis_type: str,
    source_name: str,
    line_count: int,
) -> str:
    if not findings:
        return (
            f"Analyzed {line_count} non-empty lines from {source_name}. "
            "Local rules did not find a clear high-signal Linux operations issue. "
            "Provide more context or use --cloud-llm for stronger language interpretation."
        )
    high = [item.title for item in findings if item.severity == "high"]
    medium = [item.title for item in findings if item.severity == "medium"]
    parts = [
        f"Analyzed {line_count} non-empty lines from {source_name} as {analysis_type}.",
        f"Detected {len(findings)} issue category/categories.",
    ]
    if high:
        parts.append("High priority: " + ", ".join(high) + ".")
    if medium:
        parts.append("Medium priority: " + ", ".join(medium) + ".")
    return " ".join(parts)


def _normalize_text(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _clip(text: str, limit: int) -> str:
    return text if len(text) <= limit else text[: limit - 3] + "..."
